services:
  kafka:
    image: confluentinc/cp-kafka:7.7.7
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      CLUSTER_ID: "KM2194jmaTFywaAc-HB0TMg"
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

  postgres-notifications:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: notifications
    volumes:
      - ./notification-service/migrations:/docker-entrypoint-initdb.d
      - notifications_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  notification-service:
    build: ./notification-service
    env_file:
      - ./notification-service/.env
    ports:
      - "8082:8080"
    depends_on:
      - kafka
      - postgres-notifications

  postgres-payment:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: notifications
    volumes:
      - ./payment-service/migrations:/docker-entrypoint-initdb.d
      - pgdata_payments:/var/lib/postgresql/data
    ports:
      - "5435:5432"

  payment-service:
    build: ./payment-service
    env_file:
      - ./payment-service/.env
    ports:
      - "8081:8081"
    depends_on:
      - kafka
      - postgres-payment

  postgres-order:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: orders
    volumes:
      - ./order-service/migrations:/docker-entrypoint-initdb.d
      - pgdata_orders:/varlib/postgresql/data
    ports:
      - "5433:5432"

  order-service:
    build: ./order-service
    env_file:
      - ./order-service/.env
    ports:
      - "8080:8080"
    depends_on:
      - kafka
      - postgres-order


volumes:
  pgdata_notifications:
  pgdata_payments:
  pgdata_orders: